import type { Work } from './types';

/**
 * Shopify Automation — pipeline agent yang mengubah satu link produk supplier
 * (Alibaba / 1688) jadi draft product siap review di Shopify.
 *
 * KLIEN SENGAJA DIANONIMKAN atas permintaan Umar: ditulis sebagai "a fashion
 * retailer on Shopify", tanpa nama merek maupun domain toko. Kalau suatu saat
 * boleh disebut, ganti `facts.Client` dan kalimat `summary` — sisanya sudah
 * netral.
 *
 * Banner sekarang ASLI (kartu judul dari DATA-PORTO). Sisa asetnya masih
 * placeholder — ganti dengan tangkapan layar asli sebelum ship publik.
 */
export const shopifyAutomation: Work = {
  slug: 'shopify-automation',
  title: 'Shopify Automation',
  logo: '/works/shopify-automation/shopify-automation_logo.svg',
  category: 'AI AUTOMATION | PYTHON',
  disciplines: ['ai', 'web'],
  year: '2026',
  description:
    'An agent-driven pipeline that turns one supplier product link into a review-ready Shopify draft — brand copy, linked variants, cost, size chart, and photos — with every mechanical step handled by deterministic Python rather than the model.',
  summary: [
    {
      text: 'A fashion retailer on Shopify was building product pages by hand, one supplier link at a time. ',
    },
    {
      text: 'This pipeline turns a single Alibaba or 1688 link into a review-ready draft product, and never publishes anything without a human.',
      strong: true,
    },
    {
      text: ' The architectural call is the whole system: the model decides four things, and deterministic Python does everything else — colour matching, variants, size charts, GraphQL, and a rule-by-rule verification gate run against the live store.',
    },
  ],
  services: ['AI automation', 'Pipeline engineering', 'Data extraction', 'Shopify integration'],
  facts: [
    { label: 'Client', value: 'Fashion retailer on Shopify' },
    { label: 'Role', value: 'AI automation engineer — one of two' },
    { label: 'Runtime', value: 'Python plus an agent, Shopify Admin API' },
    { label: 'Sources', value: 'Alibaba and 1688' },
  ],
  stack: ['Python', 'Shopify Admin GraphQL API', 'MCP', 'Headless browser automation'],
  challenge:
    'Two suppliers, two entirely different pages: one serves clean embedded JSON, the other serves Chinese data that only becomes English after a client-side translator finishes running — and both block robots. On top of that, a language model writing Shopify GraphQL from memory kept drifting into the wrong field names and the wrong mutation shape, and those errors only surfaced after the product already existed in the store.',
  role: 'AI automation engineer, one of two people on the project. Built the extraction, build, and verification pipeline: both supplier extractors, the deterministic build step, the mutation generators, the verification gate, and the batch driver — plus the operator commands and the rulebook that encodes the business rules as configuration rather than code.',
  approach: [
    {
      title: 'AI for judgment, code for mechanics',
      body: 'The model decides exactly four things per product: the category, the brand-facing name, the description copy, and what it can actually see in the supplier images. Colour matching, variants, tags, size charts, weights, and every line of GraphQL are generated by Python — so a low-effort run lands on the same result as a careful one.',
    },
    {
      title: 'Never let the model write the mutation',
      body: 'Scripts print the GraphQL; the agent pastes that output unchanged and dumps the response to a fixed filename for the next generator to read. The pattern exists because inline documentation was not enough — the model kept confusing two similarly named option fields until the text stopped coming from it at all.',
    },
    {
      title: 'Verify against the store, not the plan',
      body: 'A deterministic gate re-reads the product that actually exists and checks every rule on it: draft status, linked colour and size options, cost above zero, required tags present, forbidden description sections absent. Nothing reports success before that gate passes.',
    },
  ],
  outcomes: [
    { metric: '4', label: 'Decisions left to the model; the rest is deterministic' },
    { metric: '2', label: 'API calls per product, batched by design' },
    { metric: '0', label: 'Products ever published without human review' },
  ],
  banner: {
    src: '/works/shopify-automation/shopify-automation_banner.webp',
    alt: 'The Alibaba-to-Shopify pipeline in four stages: extract, classify, build, and draft.',
  },
  gallery: [
    {
      src: '/works/shopify-automation/shopify-automation_pipeline.svg',
      alt: 'Pipeline stages from extraction and vision through build, create, finalize, and verify.',
      span: 'half',
    },
    {
      src: '/works/shopify-automation/shopify-automation_rules.svg',
      alt: 'Business rules held as configuration: colour whitelist, attribute maps, and per-type tags.',
      span: 'half',
    },
    {
      src: '/works/shopify-automation/shopify-automation_graphics.svg',
      alt: 'A generated draft product: linked colour and size variants, size chart, and locked description sections.',
      span: 'full',
    },
  ],
  ogAccent: '#334155',
};
